extends SceneTree
func _init():
	print("[TEST] PortedDraw smoke")
	var node = Node2D.new()
	root.add_child(node)
	var CanvasCompat = load("res://scripts/render/CanvasCompat.gd")
	var PortedDraw = load("res://scripts/render/PortedDraw.gd")
	var ctx = CanvasCompat.new()
	ctx.bind(node)
	var pd = PortedDraw.new()
	pd.setup(ctx)
	pd.set_tick(10)
	ctx.begin_frame()
	pd.draw_bobina({"x":0,"y":0,"outfit":"og","tick":10,"iframe":0,"focus":false,"walk":0,"bombFx":0,"face":-1.57,"vx":0,"vy":0})
	print("[TEST] bobina ok")
	ctx.begin_frame()
	pd.draw_mumu({"x":0,"y":0,"r":15,"t":10,"flash":0,"icy":false,"kind":"lil"})
	print("[TEST] mumu ok")
	ctx.begin_frame()
	pd.draw_elite({"x":0,"y":0,"r":22,"t":10,"flash":0,"elite":"cheer"})
	print("[TEST] elite cheer ok")
	ctx.begin_frame()
	pd.draw_elite({"x":0,"y":0,"r":22,"t":10,"flash":0,"elite":"voideye"})
	print("[TEST] elite voideye ok")
	ctx.begin_frame()
	pd.draw_boss({"x":0,"y":0,"r":36,"flash":0,"face":1.57,"dead":false,"data":{"portrait":"ape","color":"#c9a24b"}})
	print("[TEST] boss ape ok")
	ctx.begin_frame()
	pd.draw_boss({"x":0,"y":0,"r":36,"flash":0,"face":1.57,"dead":false,"data":{"portrait":"bogdanoff","color":"#b48ce0"},"active":"igor"})
	print("[TEST] boss bogdanoff ok")
	ctx.begin_frame()
	pd.draw_bullet({"x":0,"y":0,"r":4,"col":"#ff7ad1","hp":0})
	print("[TEST] bullet ok")
	ctx.begin_frame()
	pd.draw_pshot({"x":0,"y":0,"gat":true,"vx":0,"vy":-1})
	print("[TEST] pshot gat ok")
	ctx.begin_frame()
	pd.draw_pshot({"x":0,"y":0,"laser":true,"vx":0,"vy":-1})
	print("[TEST] pshot laser ok")
	print("[TEST] ALL OK")
	quit()
