#!/usr/bin/env node
/**
 * Phase 7 — Dual QA harness structure (does NOT claim dual pass).
 * Product sign-off remains human + PARITY.md log.
 */
import { createGate, read, exists } from "./gate_lib.mjs";

const g = createGate("Phase 7 — Dual QA harness");

g.ok(exists("tools/port/dual_playtest.mjs"), "dual_playtest.mjs");
g.ok(exists("godot/scripts/tools/screenshot_playtest.gd"), "screenshot_playtest.gd");
const dual = read("tools/port/dual_playtest.mjs");
g.ok(dual.includes("--full") || dual.includes("full"), "dual supports --full");
g.ok(dual.includes("html") && dual.includes("godot"), "dual HTML + Godot paths");
g.ok(dual.includes("__kamDual") || dual.includes("setState"), "HTML state bridge for forced screens");

const shot = read("godot/scripts/tools/screenshot_playtest.gd");
g.ok(shot.includes("godot_title") && shot.includes("godot_play"), "screenshot title + play");
g.ok(shot.includes("godot_flow_stageclear") || shot.includes("stageclear"), "screenshot stage clear");
g.ok(shot.includes("godot_end_gameover") || shot.includes("GAMEOVER"), "screenshot ends");

const parity = read("godot/PARITY.md");
g.ok(/Phase 7 sign-off/i.test(parity) || /sign-off log/i.test(parity), "PARITY has Phase 7 sign-off log");
g.soft(!/^\| [^|]+ \| [^|]+ \| [^|]+ \| \*\*signed\*\*/m.test(parity), "sign-off not falsely marked signed");

// Report dir may be empty until dual runs
g.soft(exists("tools/port/playtest_out"), "playtest_out/ exists (regenerated by dual)");

g.finish();
